Update shout.css
shower/material pull request #51
Opened 2019-11-20 09:26 UTC by Kreezag

Fix incorrect display of overflowing long text.
<img width="567" alt="Идея реактивности — Реактивность Vue js 2019-11-20 12-24-36" src="https://user-images.githubusercontent.com/13301570/69226259-ea296900-0b90-11ea-9298-fbf82f9c5ad8.png">

2019-11-22 13:38 UTC, pepelsbey commented
Hmm, what am I doing wrong here and how exactly `box-sizing: border-box` would help?

When I type words with spaces they naturally break.

<img width="669" alt="image" src="https://user-images.githubusercontent.com/105274/69430048-fc98d380-0d45-11ea-9508-4dcf6e1c4b8d.png">

When the word is too long to fit it overflows

<img width="748" alt="image" src="https://user-images.githubusercontent.com/105274/69430310-60230100-0d46-11ea-96a6-2c9f46c30cfd.png">

If you want them to break, you can add invisible `&shy;` symbol that would break if the word won’t fit:

<img width="949" alt="image" src="https://user-images.githubusercontent.com/105274/69430303-58635c80-0d46-11ea-9ff4-b90c784cbea2.png">

Adding `box-sizing: border-box` doesn’t help with overflowing words.

2019-11-22 13:39 UTC, pepelsbey requested changes
I’m not sure how exactly this would help.

2019-11-23 12:48 UTC, Kreezag commented
Probably it's only my problem, but I see title offset in the list mode
<img width="840" alt="CPU History 2019-11-23 15-40-21" src="https://user-images.githubusercontent.com/13301570/69478884-87da9d80-0e08-11ea-9edc-b6aa7b2a4cad.png">

2019-11-23 13:01 UTC, pepelsbey commented
Oh my, I finally got it. Sorry it took a while. But a little explanation would’ve helped.
Thank you, I’m going to merge and release it shortly.

2019-11-23 13:02 UTC, merged